### PR TITLE
Hyperdimensional Computing vs. Neural Networks: Comparing Architecture and Learning Process

### PR DESCRIPTION
**Pull request by RunnnnWang**

### CODE REVIEW

**Review by DarthIV02 — CHANGES_REQUESTED** [review]
The review looks good, just don't forget to update the README with the new paper :)

**Comment by Orienfish** [comment]
@RunnnnWang Run, could you address Ivannia's comments here? Thanks for contributing to this reading group repo!

**Comment by RunnnnWang** [comment]
Hi! I just updated the Readme! Sorry for the delay!

**Comment by Orienfish** [comment]
@DarthIV02 Could you help with reviewing this? Thanks ;)

**Pull request merged**
