### PR TITLE
Flavio - CorruptedFewShot

### PR DESCRIPTION
**Pull request by flavio-ponzina**
my paper review on corrupted few-shot learning of 11/30/23

### CODE REVIEW

**Review by Orienfish — CHANGES_REQUESTED** [review]
Hi Flavio, thanks a bunch for participating in this Github repo :)
Most of the contents look fantastic. Just several small changes will make it better:
* It seems `template.md` and `corrupted_few_shot.md` are two duplicated files?
* It would be nice to add raw images to the markdown note, instead of adding a `.pptx` file, as the `.pptx` file is not visible on Github. You could simply add an image to the markdown file with `Loss1`, assuming your image is named as `Loss1.PNG`.
* Could you please add an entry to this paper in the root `README.md` file?

**Comment by flavio-ponzina** [comment]
Done!

**Review by Orienfish — CHANGES_REQUESTED** [review]
The first two items look perfect!
Do you mind adding an entry in the root README.md to your markdown file, just adding to the current IJCAI list? Thanks

**Comment by flavio-ponzina** [comment]
done

**Comment by Orienfish** [comment]
Thank you so much! This looks really nice!

**Pull request merged**
